### DISCUSSION TITLE
Trying to install with more flexible data directory. How to sqlite?

### DISCUSSION THREAD

**Discussion by pegasusearl** [ndom91/briefkasten#62] [Q&A]
Hello, I'm someone who reinstall operating system quite frequently so I'm trying to install Briefkasten so that it will survive those reinstall. I mean the user data.

I tried to connect /var/lib/postgresql/data to my user directory. But it's stuck at initialization. 
```
bk-postgres  | The default text search configuration will be set to "english".
bk-postgres  | 
bk-postgres  | Data page checksums are disabled.
bk-postgres  | 
bk-postgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
bk-postgres  | creating subdirectories ... ok
bk-postgres  | selecting dynamic shared memory implementation ... posix
bk-postgres  | selecting default max_connections ... 20
bk-postgres  | selecting default shared_buffers ... 400kB
bk-postgres  | selecting default time zone ... Etc/UTC
bk-postgres  | creating configuration files ... ok
bk-postgres  | 2023-06-30 05:57:50.395 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
bk-postgres  | 2023-06-30 05:57:50.395 UTC [83] HINT:  The server must be started by the user that owns the data directory.
bk-postgres  | child process exited with exit code 1
bk-postgres  | initdb: removing contents of data directory "/var/lib/postgresql/data"
bk-postgres exited with code 1

```

So I gave up that idea and trying to use sqlite instead but stuck at `db:push`. 
```
docker exec -it bk-app /bin/bash                                                                            ✔ 
nextjs@52f82e5c17c7:/app$ pnpm db:push

> briefkasten@0.9.0 db:push /app
> npx prisma db push

Prisma schema loaded from prisma/schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:9
   | 
 8 |   provider             = "postgres"
 9 |   url                  = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]

Prisma CLI Version : 4.8.1
 ELIFECYCLE  Command failed with exit code 1.
nextjs@52f82e5c17c7:/app$ 

```

How to do it properly?

----------------
Personally I prefer using sqlite. Between those two, I would love a guidance to set up briefkasten using sqlite. 
Which part did I do wrong?
.env
```
# REQUIRED - Prisma / Supabase
#DATABASE_URL=postgres://bkAdmin:briefkasten@postgres:5432/briefkasten?sslmode=disable
DATABASE_URL=file:///var/data/db.sqlite

# REQUIRED - NextAuth.js
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=something-something

GITHUB_ID=
GITHUB_SECRET=

GOOGLE_ID=
GOOGLE_SECRET=

KEYCLOAK_NAME=
KEYCLOAK_ID=
KEYCLOAK_SECRET=
KEYCLOAK_ISSUER=

# May help if getting "error=OAuthAccountNotLinked" while using Keycloak IdP, potentially dangerous(!) if TRUE, read carefully at https://next-auth.js.org/configuration/providers/oauth#allowdangerousemailaccountlinking-option
KEYCLOAK_DANGER_EMAIL_ACC_LINK=false

# Name will display on log in button, "Continue with <name>"
AUTHENTIK_NAME=
AUTHENTIK_ID=
AUTHENTIK_SECRET=
# URL to Authentik application, ie https://authentik.example.com/applications/o/briefkasten
AUTHENTIK_ISSUER=

# Optional - if set to true, will try to sign in first provider
AUTOLOGIN_FIRST_PROVIDER=

# Optional - Only required if you want to use the Email Provider for NextAuth.js
SMTP_SERVER=
SMTP_FROM=

# Optional - Supabase
# Only required if you want to use cloud object storage for Bookmark screenshots
SUPABASE_KEY=
SUPABASE_URL=
SUPABASE_BUCKET_ID=

```

docker-compose
```
version: '3.8'

services:
  postgres: #<< can I delete these if I'm using sqlite?
    container_name: bk-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bkAdmin
      - POSTGRES_PASSWORD=briefkasten
      - POSTGRES_DB=briefkasten
    ports:
      - 5432:5432
    volumes:
      - briefkasten-db:/var/lib/postgresql/data
  app:
    container_name: bk-app
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3004:3000
    depends_on:
      - 'postgres'
    volumes:
      - /mnt/warehouse/DockerData/Briefkasten/briefkasten-sqlite:/var/data
volumes:
  briefkasten-db:
```

![Screenshot_20230630_131917](https://github.com/ndom91/briefkasten/assets/23167087/07371c36-006b-42f0-9790-eda99664d768)
