### ISSUE TITLE
Adding Keycloak provider

### ISSUE THREAD

**Issue by sabirovrinat85** [ndom91/briefkasten#31]
### Describe the bug

First of all I'm far from being a developer, so lacking some "admin-friendly" :) abilities and docs leads to hard understanding how to compose pieces in a right way (while all of them seems to be here)

I want to be able to use my Keycloak instance (which is already up and connected to OpenLDAP) in Breifkasten and to turn off other enabled auth capabilities (GitHub, Google, Magic link), and using Docker container (with PostgreSQL as DB) for it.

What I've done:

  Wrote docker-compose.yml initially with official image for testing (port 5432 is already exposed, so here is 5433, and as I can see it, in docker-compose there's no need in exposing DB port because containers from the same yml config are placed in the same docker network, but anyway...), which after deploying gave - unsurprisingly - error 500 (there's no other providers in the image)

```
version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bkAdmin
      POSTGRES_PASSWORD: HIDDEN_DB_PASS
      POSTGRES_DB: briefkasten
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: ndom91/briefkasten:latest
    environment:
      DATABASE_URL: postgres://bkAdmin:HIDDEN_DB_PASS@briefkasten-postgres-1:5432/briefkasten?sslmode=disable
      NEXTAUTH_URL: https://briefkasten.HIDDENDOMAIN.ORG
      NEXTAUTH_SECRET: HIDDEN_RANDOM_SECRET
      KEYCLOAK_ID: briefkasten
      KEYCLOAK_SECRET: HIDDENSECRET_FROM_KEYCLOAKS_CLIENT_CONFIG_FOR_BRIEFKASTEN
      KEYCLOAK_ISSUER: https://keycloak.HIDDENDOMAIN.ORG/realms/briefkasten
    restart: unless-stopped
    ports:
      - "17080:3000"
    depends_on:
      - 'postgres'
volumes:
  db:
```

then

**git clone git@github.com:ndom91/briefkasten.git**

Added Keycloak provider and commented out other already included providers

**nano src/pages/api/auth/\[...nextauth\].js**

```
import NextAuth from 'next-auth'
import KeycloakProvider from 'next-auth/providers/keycloak'
#import GithubProvider from 'next-auth/providers/github'
#import GoogleProvider from 'next-auth/providers/google'
#import EmailProvider from 'next-auth/providers/email'
import { PrismaAdapter } from '@next-auth/prisma-adapter'
import prisma from '@/lib/prisma'

const providers = []

if (process.env.KEYCLOAK_ID) {
  providers.push(
    KeycloakProvider({
      clientId: process.env.KEYCLOAK_ID,
      clientSecret: process.env.KEYCLOAK_SECRET,
      issuer: process.env.KEYCLOAK_ISSUER,
    })
  )
}
#if (process.env.GITHUB_ID) {
#  providers.push(
#...CUTTING here too many commented out lines...
#      from: process.env.SMTP_FROM,
#    })
#  )
#}

export const authOptions = {
  adapter: PrismaAdapter(prisma),
  providers,
  pages: {
    signIn: '/auth/signin',
  },
  callbacks: {
    async session({ session, user }) {
      session.user.userId = user.id
      return session
    },
  },
  secret: process.env.NEXTAUTH_SECRET,
  debug: process.env.NODE_ENV !== 'production',
}

export default NextAuth(authOptions)
```

then launched

**docker build -t sabirovrinat85/briefkasten:281222 .**

which after some time of building process failed with this messages:

```
nfo  - Linting and checking validity of types...

Failed to compile.

./src/pages/api/auth/[...nextauth].js
Error: Parsing error: Private names are only allowed in property accesses (`obj.#import`) or in `in` expressions (`#import in obj`). (3:0)

./src/pages/index.jsx
123:6  Warning: React Hook useEffect has a missing dependency: 'nextauth.user'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ELIFECYCLE  Command failed with exit code 1.
The command '/bin/sh -c pnpm build' returned a non-zero code: 1
```

cannot grasp what do I need to add/delete/edit here... and I think that if for custom providers etc there's a need of editing source files and then building custom image, wouldn't it be much more convenient to map those "should edit" files in additional docker volume, so that users could use one image but accommodate it for their special requirements?

### Reproduction

needs just a little editing of [...nextauth].js

### System Info

```Shell
System:
    OS: Linux 5.15 Arch Linux
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 1.23 GB / 13.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 108.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
