### ISSUE TITLE
Login via Email Magic Link fails in Firefox

### ISSUE THREAD

**Issue by mrg358** [ndom91/briefkasten#40]
Briefkasten deployed with docker, running behind Nginx Proxy Manager.
I set up Github, Google and Email login. 
All of the three login providers works correctly in Brave (chrome).

Login via Email fails in Firefox (tested on ubuntu and android).
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error NetworkError when attempting to fetch resource. 
Object { error: {…}, url: "/api/auth/providers", message: "NetworkError when attempting to fetch resource." }
```

**Comment by ndom91** [comment]
What exactly did you do to provoke that error message? 

The error message seems to indicate that the `/api/auth/providers` endpoint is not available. But this is the endpoint which tells the login page which buttons to render, for example. Therefore, if the login page renders correctly then this endpoint _should_ be working.

Are the links in the email body correct? I.e. if its supposed to be `briefkasten.home.com/api/auth/providers`, but the email link is maybe still pointing to `localhost:3000/api/auth/providers`, this coudl cause problems as well.

**Comment by mrg358** [comment]
E-mail wasn't delivered at all. It seems this is a Firefox specific bug only. In Chrome (Brave) everything works.
Authentication stops after hitting "Submit Query" button. 
API URL shows "blocked" status and NS_BINDING_ABORTED error message.
You can take a look, here is [my deployment](https://bk.d.numeo.top)
I was searching for solutions, maybe this has something to do with default action on login button, not sure.

**Comment by ndom91** [comment]
Okay so I was able to reproduce it on your instance - thanks for providing that link :+1: 

It also worked for me in Chrome, but as you said, not in Firefox.

Can you check your Vercel API route logs for the `/api/auth/[...nextauth].js` function? That should have more info for us. Its clearly complaining about the `/api/auth/providers` endpoint, but that is available under your main domain, so that shouldn't be a problem.. 

What's your `NEXTAUTH_URL` set to? Are you using `NEXTAUTH_INTERNLA_URL` as well by chance?

**Comment by mrg358** [comment]
actually there are some callback errors in docker, I hope it helps.
https://go.numeo.top/eSNJx

here is part of my my .env vars 
```
# REQUIRED - NextAuth.js
NEXTAUTH_URL=https://bk.d.numeo.top
NEXTAUTH_URL_INTERNAL=http://10.0.0.11:3004
```

and here is my compose file
```
version: '3.8'

services:
  postgres:
    container_name: bk-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bkAdmin
      - POSTGRES_PASSWORD=<redacted>
      - POSTGRES_DB=briefkasten
        #ports:
        #- 5432:5432
    volumes:
      - briefkasten-db:/var/lib/postgresql/data
  app:
    container_name: bk-app
    labels:
      com.centurylinklabs.watchtower.enable: false
    build: .
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 10.0.0.11:3004:3000
    depends_on:
      - 'postgres'
volumes:
  briefkasten-db:
```
